version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: siteseer_mongo
    volumes:
      - ./mongo-volumes:/data/db
  site-seer:
    build: ./
    container_name: siteseer_backend
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/siteseer
    depends_on:
      - mongodb